{% extends "layouts/main.phtml" %}
{% block content %}
{% set pageID = "pgTemplates" %}
{{ partial("partials/header") }}

<div class='grid'>
    <div class='grid_column'>
        <div class="card card-block">

            <div class='templateListHead'>
                <div class='grid'>
                    <div class='grid_column -medium6'>
                        <h2 class="sectionTitle -inline">
                            Pregled svih predložaka
                        </h2>
                        <a class='btn btn-primary' href='#'>
                            Dodaj novi predlozak
                        </a>
                    </div>
                    <div class='grid_column -medium6 textRight'>
                        <form class='templateListHead_search form-inline' action=''>
                            <div class="form-group">
                                <label class="sr-only">Pretraga...</label>
                                <input type="text" class="form-control templateListHead_search_input" placeholder="Pretraga...">
                            </div>
                            <button type="submit" class="btn btn-secondary templateListHead_search_submit">
                                Trazi
                            </button>
                        </form>
                    </div>
                </div>
            </div>

            <div class='templateList'>

                <!-- Side categories -->
                <div class='templateList_sidebar'>
                    <div class='templateList_sidebar_inner'>
                        <h3 class='templateList_sidebar_title'>
                            Kategorije
                        </h3>
                        <nav class='sideCategories'>
                            <?php

                            function generateCategoryTree($categories, $categoryId, $parent = 0, $depth=0){
                                if($depth > 10)
                                {
                                    return "";
                                }
                                $tree = '<ul>';

                                $ni=count($categories);
                                for($i=0; $i < $ni; $i++){
                                    if($categories[$i]['parent_id'] == $parent){
                                        $class = "";
                                        if($categories[$i]['id'] == $categoryId)
                                        {
                                            $class = "active";
                                        }

                                        $tree .= '<li class="'.$class.'">';
                                        $tree .= Phalcon\Tag::linkTo(
                                            array(
                                                array('for' => 'template-category', 'category' => $categories[$i]['id']),
                                                $categories[$i]['name'],
                                                'class' => $class
                                            )
                                        );
                                        $tree .= '</li>';
                                        $tree .= generateCategoryTree($categories, $categoryId, $categories[$i]['id'], $depth+1);
                                    }
                                }

                                $tree .= '</ul>';
                                return $tree;
                            }

                            echo(generateCategoryTree($categories, $categoryId));
                            ?>
                        </nav>
                    </div>
                </div>

                <!-- Template list -->
                <div class='templateList_content'>
                    <div class='templateList_content_inner'>
                        <div class='table-responsive'>
                            <table class="table table-hover -edge templateTable">
                                <thead>
                                    <tr>
                                        <th class='templateTable_id'>Broj</th>
                                        <th class='templateTable_date'>Datum</th>
                                        <th class='templateTable_code'>Oznaka</th>
                                        <th class='templateTable_title'>Naziv</th>
                                        <th class='templateTable_status'>Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for t in page.items %}
                                    <tr>
                                        <td class='templateTable_id'>{{ t.id }}</td>
                                        <td class='templateTable_date'>{{ t.updated_at }}</td>
                                        <td class='templateTable_tag'>{{ t.tag }}</td>
                                        <td class='templateTable_name'><a class='link' href='#'>{{ t.name }}</a></td>
                                        <td class='templateTable_status'>Neodobren</td>
                                        <td class='table_adminCell'>
                                            <a href='#' class='table_adminCell_item'>
                                                <img class='icon -h16 table_adminCell_icon -edit' src='../public/icons/edit.svg' alt=''>
                                            </a>
                                            <a class='table_adminCell_item'>
                                                <img class='icon -h16 table_adminCell_icon -delete' src='../public/icons/delete.svg' alt=''>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{{ partial("partials/footer") }}
{% endblock %}
