<nav>
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="./list?page=<?= $page->before; ?>" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <?php
        for ($i = 1; $i <= $page->last; $i++){
      ?>
            <li class="page-item"><a class="page-link" href="./list?page=<?= $i ?>"><?php echo $i; ?></a></li>
      <?php
        }
      ?>
      <li class="page-item">
        <a class="page-link" href="./list?page=<?= $page->next; ?>" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    </ul>
</nav>