{% extends "layouts/main.phtml" %}
{% block content %}
{% set pageID = "pgUsers" %}
{{ partial("partials/header") }}

<form method='POST' action="../save">
   <div class='grid'>
      <div class='grid_column'>
        {{ form.render("id") }}
        <fieldset class="form-group">
          <label>Korisničko ime</label>
          {{ form.render("name") }}
        </fieldset>
        <fieldset class="form-group">
          <label>Email</label>
          {{ form.render("email") }}
        </fieldset>
        <fieldset class="form-group">
          <label>Lozinka</label>
          {{ form.render("password") }}
        </fieldset>
        <fieldset class="form-group">
          <label>Privilegije</label>
          <div class="checkbox">
            <label>
              {{ form.render("add_templates") }}
              Add templates
            </label>
          </div>
          <div class="checkbox">
            <label>
              {{ form.render("add_users") }}
              Add users
            </label>
          </div>
          <div class="checkbox">
            <label>
              {{ form.render("add_alarms") }}
              Add alarms
            </label>
          </div>
        </fieldset>
        <button type="submit" class="btn btn-primary">Uredi korisnika</button>
        <a href="../list"><button type="button" class="btn btn-neutral">Odustani</button></a>
      </div>
    </div>
</form>

{{ partial("partials/footer") }}
{% endblock %}
