{% extends "layouts/main.phtml" %}
{% block content %}
{% set pageID = "pgUsers" %}
{{ partial("partials/header") }}

  <div class='grid'>
    <div class='grid_column'>
      <h2 class="pageTitle -inline">Korisnici</h2>
      <a class='btn btn-primary' data-toggle="modal" data-target="#userModal">
        Dodaj novog korisnika
      </a>

      <table class="table table-hover -edge">
        <thead>
          <tr>
            <th>Korisnicko ime</th>
            <th>Datum kreiran</th>
            <th>Privilegije</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <?php
            foreach ($page->items as $user) {
            ?>
               <tr>
                <td scope="row"><?php echo $user->name ?></td>
                <td><?php echo date('d.m.Y, H:i', strtotime($user->created_at)); ?></td>
                <td>
                <?php
                    $output = '';
                    foreach ($user->role as $userRole){
                        $output .= $userRole->name . ', ';
                    }
                    $output = rtrim($output, ', ');
                    echo $output;
                 ?>
                 </td>
                <td class='table_adminCell'>
                  <a class='table_adminCell_item' href='edit/<?php echo $user->id ?>'>
                    <img class='icon -h16 table_adminCell_icon -edit' src='../public/icons/edit.svg' alt=''>
                  </a>
                  <a class='table_adminCell_item'>
                    <img class='icon -h16 table_adminCell_icon -delete' src='../public/icons/delete.svg' alt=''>
                  </a>
                </td>
              </tr>
              <tr>
            <?php
            }
            ?>
        </tbody>
      </table>
    
    {{ partial("partials/pagination") }}
      
    </div>
  </div>

  <!-- Add user modal -->
  <div class="modal fade" id='userModal'>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Dodaj novog korisnika</h4>
        </div>
        <form method='POST' action='create'>
          <div class="modal-body">
            <fieldset class="form-group">
              <label>Korisničko ime</label>
              {{ form.render("name") }}
            </fieldset>
            <fieldset class="form-group">
              <label>Email</label>
              {{ form.render("email") }}
            </fieldset>
            <fieldset class="form-group">
              <div class='grid -clean'>
                <div class='grid_column -small6'>
                  <label>Lozinka</label>
                  {{ form.render("password") }}
                </div>
                <div class='grid_column -small6'>
                  <label>Ponovi lozinku</label>
                  {{ form.render("password_repeat") }}
                </div>
              </div>
            </fieldset>
            <fieldset class="form-group">
              <label>Privilegije</label>
              <div class="checkbox">
                <label>
                  {{ form.render("add_templates") }}
                  Add templates
                </label>
              </div>
              <div class="checkbox">
                <label>
                  {{ form.render("add_users") }}
                  Add users
                </label>
              </div>
              <div class="checkbox">
                <label>
                  {{ form.render("add_alarms") }}
                  Add alarms
                </label>
              </div>
            </fieldset>
            <!--
            <fieldset class="form-group">
              <label>Statusi</label>
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="" checked>
                  Račun aktivan
                </label>
              </div>
            </fieldset>
            -->
          
          </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-primary">Dodaj korisnika</button>
              <button type="button" class="btn btn-neutral" data-dismiss="modal">Odustani</button>
            </div>
        </form>
      </div>
    </div>
  </div>
{{ partial("partials/footer") }}
{% endblock %}
