<!doctype html>

<head>
    <meta charset='utf-8'>
    <link rel='dns-prefetch' href='https://fonts.googleapis.com'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
    <meta name='viewport' content='width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0'>
    <meta name='msapplication-tap-highlight' content='no'>
    <title>{{ pageTitle }}</title>

    <!-- CSS -->
    {{ assets.outputCss() }}


</head>

<body>
{% block content %}{% endblock %}

    <!-- Script files -->
    {{ assets.outputJs() }}

</body>

</html>
